backend:
  name: github
  repo: hebeconsulting/hebeconsulting.github.io
  branch: master
  site_domain: vigorous-mccarthy-d5086d.netlify.app

media_folder: "images/uploads"

collections:
  - label: "English Blog" # Used in the UI
    name: "english_blog" # Used in routes, e.g., /admin/collections/blog
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    filter: {field: "lang", value: "en"}
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Language", name: "lang", widget: "select", options: ["en", "tr"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Turkish Blog" # Used in the UI
    name: "turk_blog" # Used in routes, e.g., /admin/collections/blog
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    filter: {field: "lang", value: "tr"}
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Language", name: "lang", widget: "select", options: ["en", "tr"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
